name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mini-saas-tracker/backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint backend
        run: flake8 app

  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mini-saas-tracker/frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Lint frontend
        run: npm run lint || true

  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mini-saas-tracker/backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Run tests with coverage
        run: pytest --cov=app --cov-report=term-missing

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mini-saas-tracker/frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run frontend tests
        run: npm run test || true

  build-backend-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build backend Docker image
        run: docker build -t backend:ci mini-saas-tracker/backend

  build-frontend-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build frontend Docker image
        run: docker build -t frontend:ci mini-saas-tracker/frontend

  migrate-db:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mini-saas-tracker/backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install alembic
      - name: Run migrations
        run: alembic upgrade head
